In [10]:
data = [{'age' : 4, 'height' : 96.0, 'distance' : 23},
        {'age' : 1, 'height' : 73.9, 'distance' : 45},
        {'age' : 3, 'height' : 88.9, 'distance' :np.nan},
        {'age' : 2, 'height' : 81.6, 'distance' :30}]

# Lec-1

In [1]:
import numpy as np
import pandas as pd

In [12]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
x = dv.fit_transform(data)
print(x)

[[ 4.  23.  96. ]
 [ 1.  45.  73.9]
 [ 3.   nan 88.9]
 [ 2.  30.  81.6]]


In [13]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')
si.fit_transform(x)

array([[ 4.        , 23.        , 96.        ],
       [ 1.        , 45.        , 73.9       ],
       [ 3.        , 32.66666667, 88.9       ],
       [ 2.        , 30.        , 81.6       ]])

In [14]:
data_knn = [{'age' : 4, 'height' : 96.0, 'distance' : 23},
        {'age' : 1, 'height' : 73.9, 'distance' : 45},
        {'age' : 3, 'height' : 88.9, 'distance' :np.nan},
        {'age' : 2, 'height' : 81.6, 'distance' :30}]

In [15]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
x = dv.fit_transform(data)
print(x)

[[ 4.  23.  96. ]
 [ 1.  45.  73.9]
 [ 3.   nan 88.9]
 [ 2.  30.  81.6]]


In [16]:
x

array([[ 4. , 23. , 96. ],
       [ 1. , 45. , 73.9],
       [ 3. ,  nan, 88.9],
       [ 2. , 30. , 81.6]])

In [ ]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors = 1, weights = "uniform")
knni.fit_transform(x)

In [ ]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors = 1, weights = "uniform")
knni.fit_transform(x)

In [ ]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors = 3, weights = "uniform")
knni.fit_transform(x)

## AQ: 2.1

In [ ]:
 data_aq = [{'#courses_opted': 4, 'GPA': 6.7},{'#courses_opted': 4, 'GPA': 8.5},
         {'#courses_opted': 2, 'GPA': 8.1},{'#courses_opted': 1, 'GPA': 7.2},
         {'#courses_opted': 1, 'GPA': 9.1}]

In [ ]:
 from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
data_transformed = dv.fit_transform(data)
data_transformed[:2]

# Lec 2

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
x = np.array([4,3,2,5,6])
x.reshape(1,-1)

array([[4, 3, 2, 5, 6]])

In [33]:
a = np.array([[1,2,4],[10,20,30],[23,17,47]])

In [34]:
np.mean(a)

17.11111111111111

In [35]:
ss = StandardScaler()
ss.fit_transform(a)

array([[-1.14423088, -1.3970014 , -1.30072966],
       [-0.14764269,  0.88900089,  0.16966039],
       [ 1.29187357,  0.50800051,  1.13106927]])

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
print(a)

[[ 1  2  4]
 [10 20 30]
 [23 17 47]]


In [38]:
mms = MinMaxScaler()
mms.fit_transform(a)

array([[0.        , 0.        , 0.        ],
       [0.40909091, 1.        , 0.60465116],
       [1.        , 0.83333333, 1.        ]])

In [39]:
from sklearn.preprocessing import MaxAbsScaler

In [40]:
mas= MaxAbsScaler()
mas.fit_transform(a,)

array([[0.04347826, 0.1       , 0.08510638],
       [0.43478261, 1.        , 0.63829787],
       [1.        , 0.85      , 1.        ]])

In [30]:
?MaxAbsScaler

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2)
pf.fit_transform(x)

In [2]:

x = np.array([0,3,6])
print(np.mean(x))

print(np.std(x))

3.0
6.0
2.449489742783178


In [3]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1], [2], [3]])
ft = FunctionTransformer(np.mean)
ft.fit_transform(X)

2.0

In [4]:
X

array([[1],
       [2],
       [3]])

In [5]:
ft

FunctionTransformer(func=<function mean at 0x000001F93E70B5E0>)

# PA

In [3]:

data_url = 'https://docs.google.com/spreadsheets/d/1XePXtNHcvJpCxAp4F7i8upB1QLTQJG7-/edit?usp=sharing&ouid=103622359275953448721&rtpof=true&sd=true'


data = pd.read_csv(data_url, sep = ";")
data.head()

ParserError: Error tokenizing data. C error: Expected 7 fields in line 5, saw 306


In [4]:
import pandas as pd
data_url = 'https://drive.google.com/file/d/1lvvHj0v9LKwe6XUezgpIUY_c0HdJUcCb/view'

data = pd.read_csv(data_url, sep = ";")
data.head()

HTTPError: HTTP Error 429: Too Many Requests

In [6]:
dataset = pd.read_csv("DataPreprocessingGraded_dataset.csv")


In [7]:
dataset.head()

V1    V2       V3    V4        V5 Target
0  2.0  50.0  12500.0  98.0  NEGATIVE    YES
1  0.0  13.0   3250.0  28.0  NEGATIVE    YES
2    ?     ?   4000.0  35.0  NEGATIVE    YES
3    ?  20.0   5000.0  45.0  NEGATIVE    YES
4  1.0  24.0   6000.0  77.0  NEGATIVE     NO

In [9]:
type(dataset)

pandas.core.frame.DataFrame

In [13]:
dataset.shape

(748, 6)

In [16]:
dataset.target_labels

AttributeError: 'DataFrame' object has no attribute 'target_labels'

In [17]:
dataset.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'Target'], dtype='object')