In [55]:
import numpy as np
import pandas as pd
data = [{'age' : 4, 'height' : 96.0, 'distance' : 23},
        {'age' : 1, 'height' : 73.9, 'distance' : 45},
        {'age' : 3, 'height' : 88.9, 'distance' :np.nan},
        {'age' : 2, 'height' : 81.6, 'distance' :30}]

# Lec-1

In [31]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
x = dv.fit_transform(data)
print(x)

[[ 4.  23.  96. ]
 [ 1.  45.  73.9]
 [ 3.   nan 88.9]
 [ 2.  30.  81.6]]


In [32]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')
si.fit_transform(x)

array([[ 4.        , 23.        , 96.        ],
       [ 1.        , 45.        , 73.9       ],
       [ 3.        , 32.66666667, 88.9       ],
       [ 2.        , 30.        , 81.6       ]])

In [33]:
data_knn = [{'age' : 4, 'height' : 96.0, 'distance' : 23},
        {'age' : 1, 'height' : 73.9, 'distance' : 45},
        {'age' : 3, 'height' : 88.9, 'distance' :np.nan},
        {'age' : 2, 'height' : 81.6, 'distance' :30}]

In [34]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
x = dv.fit_transform(data)
print(x)

[[ 4.  23.  96. ]
 [ 1.  45.  73.9]
 [ 3.   nan 88.9]
 [ 2.  30.  81.6]]


In [35]:
x

array([[ 4. , 23. , 96. ],
       [ 1. , 45. , 73.9],
       [ 3. ,  nan, 88.9],
       [ 2. , 30. , 81.6]])

In [36]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors = 1, weights = "uniform")
knni.fit_transform(x)

array([[ 4. , 23. , 96. ],
       [ 1. , 45. , 73.9],
       [ 3. , 23. , 88.9],
       [ 2. , 30. , 81.6]])

In [37]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors = 1, weights = "uniform")
knni.fit_transform(x)

array([[ 4. , 23. , 96. ],
       [ 1. , 45. , 73.9],
       [ 3. , 23. , 88.9],
       [ 2. , 30. , 81.6]])

In [38]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors = 3, weights = "uniform")
knni.fit_transform(x)

array([[ 4.        , 23.        , 96.        ],
       [ 1.        , 45.        , 73.9       ],
       [ 3.        , 32.66666667, 88.9       ],
       [ 2.        , 30.        , 81.6       ]])

## AQ: 2.1

In [39]:
data_aq = [{'#courses_opted': 4, 'GPA': 6.7},{'#courses_opted': 4, 'GPA': 8.5},
         {'#courses_opted': 2, 'GPA': 8.1},{'#courses_opted': 1, 'GPA': 7.2},
         {'#courses_opted': 1, 'GPA': 9.1}]

In [40]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
data_transformed = dv.fit_transform(data)
data_transformed[:2]

array([[ 4. , 23. , 96. ],
       [ 1. , 45. , 73.9]])

# Lec 2

In [41]:
from sklearn.preprocessing import StandardScaler

In [54]:
x = np.array([4,3,2,5,6])
x.reshape(1,-1)

array([[4, 3, 2, 5, 6]])

In [43]:
a = np.array([[1,2,4],[10,20,30],[23,17,47]])

In [44]:
np.mean(a)

17.11111111111111

In [45]:
ss = StandardScaler()
ss.fit_transform(a)

array([[-1.14423088, -1.3970014 , -1.30072966],
       [-0.14764269,  0.88900089,  0.16966039],
       [ 1.29187357,  0.50800051,  1.13106927]])

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
print(a)

[[ 1  2  4]
 [10 20 30]
 [23 17 47]]


In [48]:
mms = MinMaxScaler()
mms.fit_transform(a)

array([[0.        , 0.        , 0.        ],
       [0.40909091, 1.        , 0.60465116],
       [1.        , 0.83333333, 1.        ]])

In [49]:
from sklearn.preprocessing import MaxAbsScaler

In [50]:
mas= MaxAbsScaler()
mas.fit_transform(a,)

array([[0.04347826, 0.1       , 0.08510638],
       [0.43478261, 1.        , 0.63829787],
       [1.        , 0.85      , 1.        ]])

In [51]:
?MaxAbsScaler

In [52]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2)
pf.fit_transform(x)

ValueError: Expected 2D array, got 1D array instead:
array=[4 3 2 5 6].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:

x = np.array([0,3,6])
print(np.mean(x))

print(np.std(x))

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1], [2], [3]])
ft = FunctionTransformer(np.mean)
ft.fit_transform(X)

In [ ]:
X

In [ ]:
ft

# PA

In [58]:
dataset = pd.read_csv("DataPreprocessingGraded_dataset.csv")


In [ ]:
dataset.head()

In [63]:
type(dataset)

pandas.core.frame.DataFrame

In [ ]:
dataset.shape

In [ ]:
dataset.target_labels #see how to make this into bunch if possible

In [ ]:
dataset.columns

In [57]:
from sklearn.impute import SimpleImputer
sii = SimpleImputer(strategy='mean')
sii.fit_transform(dataset)

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: '?'

In [59]:
dataset.data[:5]

AttributeError: 'DataFrame' object has no attribute 'data'

In [60]:
dataset.DataFrame

AttributeError: 'DataFrame' object has no attribute 'DataFrame'

In [61]:
dataset.iloc[:4]

V1    V2       V3    V4        V5 Target
0  2.0  50.0  12500.0  98.0  NEGATIVE    YES
1  0.0  13.0   3250.0  28.0  NEGATIVE    YES
2    ?     ?   4000.0  35.0  NEGATIVE    YES
3    ?  20.0   5000.0  45.0  NEGATIVE    YES

In [62]:
feature_list = data.columns[:-1].values

AttributeError: 'list' object has no attribute 'columns'

In [64]:
dataset.dtypes

V1         object
V2         object
V3        float64
V4        float64
V5         object
Target     object
dtype: object